---

- name: Wait 300 seconds for remote host to become usable
  wait_for_connection:
    connect_timeout: 5
    delay: 2
    sleep: 1
    timeout: 300

- name: Gather system facts
  setup:

- name: Update apt cache if needed
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: yes

- block:
  - name: Fetching packages
    set_fact:
      packages: "{{ lookup('file', item)}}"
    with_first_found:
      - "{{role_path}}/vars/{{apt_installs}}"
      - "{{role_path}}/defaults/{{apt_installs}}"

  - name: Installing Packages
    apt:
      name: "{{item}}"
      state: present
      update_cache: no
    with_items:
      - "{{packages.split('\n')}}"
  when: apt_installs is defined
  become: yes
